// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include "arduino_secrets.h"
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onFHumidityChange();
void onFLightBrightnessChange();
void onFTemperatureChange();
void onSetRGBColorChange();
void onIntSetModeChange();

float fHumidity;
float fLightBrightness;
float fTemperature;
CloudColoredLight setRGBColor;
int intSetMode;

void initProperties(){

  ArduinoCloud.addProperty(fHumidity, READWRITE, ON_CHANGE, onFHumidityChange);
  ArduinoCloud.addProperty(fLightBrightness, READWRITE, ON_CHANGE, onFLightBrightnessChange);
  ArduinoCloud.addProperty(fTemperature, READWRITE, ON_CHANGE, onFTemperatureChange);
  ArduinoCloud.addProperty(setRGBColor, READWRITE, ON_CHANGE, onSetRGBColorChange);
  ArduinoCloud.addProperty(intSetMode, READWRITE, ON_CHANGE, onIntSetModeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
